services:
  identity-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001
    volumes:
      - ./certs:/app/certs
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=identity_admin
      - POSTGRES_PASSWORD=identity_password
      - POSTGRES_DB=identity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: build # Use the 'build' stage from Dockerfile
    volumes:
      - .:/workspace:cached # Mount the project root
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socket
    working_dir: /workspace
    command: sleep infinity # Keep the container running
    user: vscode # Match remoteUser in devcontainer.json

volumes:
  postgres_data:
