version: '3.8'

services:
  identity-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001
    volumes:
      - ./certs:/app/certs
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=identity_admin
      - POSTGRES_PASSWORD=identity_password
      - POSTGRES_DB=identity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: